"""Contains all the variables used including the user's items and stats and variables which control whether sections of the program run."""

gold = 0
provs = 10
hero = [0, 0, 0]
init_hero = []
equipment = []
dice_num = 0
dice_num2 = 0
fighting = False
escape = False
river = False
fight_tuto_done = False
provs_tuto_done = False
checkpoint = 0
profile_name = ""
decision_1 = ""
decision_2 = ""
decision_3 = ""
decision_4 = ""
decision_5 = ""
decision_6 = ""
decision_7 = ""
decision_8 = ""
decision_9 = ""
decision_10 = ""
decision_11 = ""
decision_12 = ""
decision_13 = ""
decision_14 = ""
decision_15 = ""
decision_16 = ""
decision_17 = ""
decision_18 = ""